services:
  nats:
    image: docker.io/nats:latest
    ports:
      - "4222:4222"
      - "8222:8222" # For monitoring
    command:
      - "-js"

  config-loader:
    build:
      context: .
      dockerfile: ./configloader/Dockerfile
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./configs:/app/configs