services:
  nats:
    image: docker.io/nats:latest
    ports:
      - "4222:4222"
      - "8222:8222" # For monitoring
    command:
      - "-js"

  postgres-fba1977e:
    image: postgres:latest
    container_name: postgres-fba1977e
    environment:
      POSTGRES_DB: c3f106287d67
      POSTGRES_USER: fba1977e
      POSTGRES_PASSWORD: fba1977e-6359-4292-9405-c3f106287d67
    ports:
      - "5433:5432"
    volumes:
      - postgres-fba1977e_data:/var/lib/postgresql/data

  postgres-1f65e1cf:
    image: postgres:latest
    container_name: postgres-1f65e1cf
    environment:
      POSTGRES_DB: 5f93ac4a5894
      POSTGRES_USER: 1f65e1cf
      POSTGRES_PASSWORD: 1f65e1cf-7a57-4e4b-8e1b-5f93ac4a5894
    ports:
      - "5434:5432"
    volumes:
      - postgres-1f65e1cf_data:/var/lib/postgresql/data

  postgres-d84ae75d:
    image: postgres:latest
    container_name: postgres-d84ae75d
    environment:
      POSTGRES_DB: e18a1046226a
      POSTGRES_USER: d84ae75d
      POSTGRES_PASSWORD: d84ae75d-f795-4be5-8979-e18a1046226a
    ports:
      - "5435:5432"
    volumes:
      - postgres-d84ae75d_data:/var/lib/postgresql/data

  config-loader:
    build:
      context: .
      dockerfile: ./configloader/Dockerfile
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./configs:/app/configs

  random-modifier:
    build:
      context: .
      dockerfile: configmodifier/Dockerfile
    volumes:
      - ./configs:/app/configs

  service-6b631a97:
    build:
      context: .
      dockerfile: services/srvone/Dockerfile
    depends_on:
      - nats
      - config-loader
      - postgres-fba1977e
      - postgres-1f65e1cf
      - postgres-d84ae75d
    volumes:
      - ./configs/cfg.6b631a97-b02f-4d77-8366-4a75f99b3d26.yaml:/app/configs/cfg.6b631a97-b02f-4d77-8366-4a75f99b3d26.yaml
    environment:
      - CONFIG_PATH=/app/configs/cfg.6b631a97-b02f-4d77-8366-4a75f99b3d26.yaml
      - NATS_URL=nats://nats:4222

  service-9fd2041b:
    build:
      context: .
      dockerfile: services/srvthree/Dockerfile
    depends_on:
      - nats
      - config-loader
      - postgres-fba1977e
      - postgres-1f65e1cf
      - postgres-d84ae75d
    volumes:
      - ./configs/cfg.9fd2041b-88bc-4ac1-8157-0188d37d0f75.yaml:/app/configs/cfg.9fd2041b-88bc-4ac1-8157-0188d37d0f75.yaml
    environment:
      - CONFIG_PATH=/app/configs/cfg.9fd2041b-88bc-4ac1-8157-0188d37d0f75.yaml
      - NATS_URL=nats://nats:4222

  service-e079e8d7:
    build:
      context: .
      dockerfile: services/srvtwo/Dockerfile
    depends_on:
      - nats
      - config-loader
      - postgres-fba1977e
      - postgres-1f65e1cf
      - postgres-d84ae75d
    volumes:
      - ./configs/cfg.e079e8d7-9153-42a0-8b4c-d4e0022c2e6b.yaml:/app/configs/cfg.e079e8d7-9153-42a0-8b4c-d4e0022c2e6b.yaml
    environment:
      - CONFIG_PATH=/app/configs/cfg.9fd2041b-88bc-4ac1-8157-0188d37d0f75.yaml
      - NATS_URL=nats://nats:4222

volumes:
  postgres-fba1977e_data:
  postgres-1f65e1cf_data:
  postgres-d84ae75d_data: