database:
    host: postgres://d84ae75d:d84ae75d-f795-4be5-8979-e18a1046226a@postgres-d84ae75d/e18a1046226a?sslmode=disable
logging:
    level: ERROR
    format: text
features:
    enable_feature_x: true
    enable_feature_y: true
