database:
  host: db.service3.local
  port: 5432
  name: service3_db
  user: service3_user
  password: service3_password

logging:
  level: WARN
  format: json

features:
  enable_feature_c: false
  enable_feature_d: true
