database:
    host: postgres://1f65e1cf:1f65e1cf-7a57-4e4b-8e1b-5f93ac4a5894@postgres-1f65e1cf/5f93ac4a5894?sslmode=disable
logging:
    level: DEBUG
    format: text
features:
    enable_feature_x: false
    enable_feature_y: true
