database:
  host: db.service2.local
  port: 5432
  name: service2_db
  user: service2_user
  password: service2_password

logging:
  level: DEBUG
  format: text

features:
  enable_feature_a: true
  enable_feature_b: true
