database:
    host: postgres://fba1977e:fba1977e-6359-4292-9405-c3f106287d67@postgres-fba1977e/c3f106287d67?sslmode=disable
nats:
    host: ""
logging:
    level: ERROR
    format: text
features:
    enable_feature_x: false
    enable_feature_y: false
