database:
  host: db.service1.local
  port: 5432
  name: service1_db
  user: service1_user
  password: service1_password

logging:
  level: INFO
  format: json

features:
  enable_feature_x: true
  enable_feature_y: false
