database:
    user: postgres://d84ae75d:d84ae75d-f795-4be5-8979-e18a1046226a@localhost:5435/e18a1046226a?sslmode=disable
logging:
    level: DEBUG
    format: text
features:
    enable_feature_x: false
    enable_feature_y: true
