app:
  name: e079e8d7-9153-42a0-8b4c-d4e0022c2e6b
  version: 1.0.0
  key_value_bucket: configs
  config_path: ./configs/cfg.e079e8d7-9153-42a0-8b4c-d4e0022c2e6b.yaml

nats:
  host: nats://0.0.0.0:4222

server:
  host: localhost
  port: 8989